// <auto-generated />
using System;
using MP1.AssetTracker.DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AssetTracker.DataLayer.Migrations
{
    [DbContext(typeof(AssetTrackerDbContext))]
    [Migration("20210325225543_Migration.v2")]
    partial class Migrationv2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MP1.AssetTracker.Model.Asset", b =>
                {
                    b.Property<int>("AssetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("OfficeID")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime");

                    b.HasKey("AssetID");

                    b.ToTable("Assets");

                    b.HasDiscriminator<string>("AssetType").HasValue("Asset");
                });

            modelBuilder.Entity("MP1.AssetTracker.Model.Office", b =>
                {
                    b.Property<int>("OfficeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Culture")
                        .IsRequired()
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("OfficeID");

                    b.ToTable("Offices");
                });

            modelBuilder.Entity("MP1.AssetTracker.Model.Cellphone", b =>
                {
                    b.HasBaseType("MP1.AssetTracker.Model.Asset");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("PhoneOperator")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.HasDiscriminator().HasValue("Cellphone");
                });

            modelBuilder.Entity("MP1.AssetTracker.Model.Computer", b =>
                {
                    b.HasBaseType("MP1.AssetTracker.Model.Asset");

                    b.Property<string>("OperatingSystem")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Processor")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("RAM")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.HasDiscriminator().HasValue("Computer");
                });
#pragma warning restore 612, 618
        }
    }
}
